// Package projects provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package projects

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ProjectPlatform.
const (
	ProjectPlatformAndroid ProjectPlatform = "android"
	ProjectPlatformCustom  ProjectPlatform = "custom"
	ProjectPlatformIos     ProjectPlatform = "ios"
	ProjectPlatformWeb     ProjectPlatform = "web"
)

// Valid indicates whether the value is a known member of the ProjectPlatform enum.
func (e ProjectPlatform) Valid() bool {
	switch e {
	case ProjectPlatformAndroid:
		return true
	case ProjectPlatformCustom:
		return true
	case ProjectPlatformIos:
		return true
	case ProjectPlatformWeb:
		return true
	default:
		return false
	}
}

// Defines values for ProjectSdks.
const (
	ProjectSdksAndroid    ProjectSdks = "android"
	ProjectSdksAndroidTv  ProjectSdks = "android_tv"
	ProjectSdksIos        ProjectSdks = "ios"
	ProjectSdksJava       ProjectSdks = "java"
	ProjectSdksJavascript ProjectSdks = "javascript"
	ProjectSdksNode       ProjectSdks = "node"
	ProjectSdksPhp        ProjectSdks = "php"
	ProjectSdksPython     ProjectSdks = "python"
	ProjectSdksRuby       ProjectSdks = "ruby"
	ProjectSdksTvOs       ProjectSdks = "tv_os"
)

// Valid indicates whether the value is a known member of the ProjectSdks enum.
func (e ProjectSdks) Valid() bool {
	switch e {
	case ProjectSdksAndroid:
		return true
	case ProjectSdksAndroidTv:
		return true
	case ProjectSdksIos:
		return true
	case ProjectSdksJava:
		return true
	case ProjectSdksJavascript:
		return true
	case ProjectSdksNode:
		return true
	case ProjectSdksPhp:
		return true
	case ProjectSdksPython:
		return true
	case ProjectSdksRuby:
		return true
	case ProjectSdksTvOs:
		return true
	default:
		return false
	}
}

// Defines values for ProjectStatus.
const (
	ProjectStatusActive   ProjectStatus = "active"
	ProjectStatusArchived ProjectStatus = "archived"
)

// Valid indicates whether the value is a known member of the ProjectStatus enum.
func (e ProjectStatus) Valid() bool {
	switch e {
	case ProjectStatusActive:
		return true
	case ProjectStatusArchived:
		return true
	default:
		return false
	}
}

// Defines values for ProjectThirdPartyPlatform.
const (
	Salesforce ProjectThirdPartyPlatform = "salesforce"
)

// Valid indicates whether the value is a known member of the ProjectThirdPartyPlatform enum.
func (e ProjectThirdPartyPlatform) Valid() bool {
	switch e {
	case Salesforce:
		return true
	default:
		return false
	}
}

// Defines values for ProjectUpdateStatus.
const (
	ProjectUpdateStatusActive   ProjectUpdateStatus = "active"
	ProjectUpdateStatusArchived ProjectUpdateStatus = "archived"
)

// Valid indicates whether the value is a known member of the ProjectUpdateStatus enum.
func (e ProjectUpdateStatus) Valid() bool {
	switch e {
	case ProjectUpdateStatusActive:
		return true
	case ProjectUpdateStatusArchived:
		return true
	default:
		return false
	}
}

// Defines values for WebSnippetLibrary.
const (
	WebSnippetLibraryJquery1113Full WebSnippetLibrary = "jquery-1.11.3-full"
	WebSnippetLibraryJquery1113Trim WebSnippetLibrary = "jquery-1.11.3-trim"
	WebSnippetLibraryJquery164Full  WebSnippetLibrary = "jquery-1.6.4-full"
	WebSnippetLibraryJquery164Trim  WebSnippetLibrary = "jquery-1.6.4-trim"
	WebSnippetLibraryNone           WebSnippetLibrary = "none"
)

// Valid indicates whether the value is a known member of the WebSnippetLibrary enum.
func (e WebSnippetLibrary) Valid() bool {
	switch e {
	case WebSnippetLibraryJquery1113Full:
		return true
	case WebSnippetLibraryJquery1113Trim:
		return true
	case WebSnippetLibraryJquery164Full:
		return true
	case WebSnippetLibraryJquery164Trim:
		return true
	case WebSnippetLibraryNone:
		return true
	default:
		return false
	}
}

// Defines values for WebSnippetVisitorIdLocatorType.
const (
	WebSnippetVisitorIdLocatorTypeCookie       WebSnippetVisitorIdLocatorType = "cookie"
	WebSnippetVisitorIdLocatorTypeJs           WebSnippetVisitorIdLocatorType = "js"
	WebSnippetVisitorIdLocatorTypeLocalStorage WebSnippetVisitorIdLocatorType = "localStorage"
	WebSnippetVisitorIdLocatorTypeQuery        WebSnippetVisitorIdLocatorType = "query"
)

// Valid indicates whether the value is a known member of the WebSnippetVisitorIdLocatorType enum.
func (e WebSnippetVisitorIdLocatorType) Valid() bool {
	switch e {
	case WebSnippetVisitorIdLocatorTypeCookie:
		return true
	case WebSnippetVisitorIdLocatorTypeJs:
		return true
	case WebSnippetVisitorIdLocatorTypeLocalStorage:
		return true
	case WebSnippetVisitorIdLocatorTypeQuery:
		return true
	default:
		return false
	}
}

// Defines values for WebSnippetUpdateLibrary.
const (
	WebSnippetUpdateLibraryJquery1113Full WebSnippetUpdateLibrary = "jquery-1.11.3-full"
	WebSnippetUpdateLibraryJquery1113Trim WebSnippetUpdateLibrary = "jquery-1.11.3-trim"
	WebSnippetUpdateLibraryJquery164Full  WebSnippetUpdateLibrary = "jquery-1.6.4-full"
	WebSnippetUpdateLibraryJquery164Trim  WebSnippetUpdateLibrary = "jquery-1.6.4-trim"
	WebSnippetUpdateLibraryNone           WebSnippetUpdateLibrary = "none"
)

// Valid indicates whether the value is a known member of the WebSnippetUpdateLibrary enum.
func (e WebSnippetUpdateLibrary) Valid() bool {
	switch e {
	case WebSnippetUpdateLibraryJquery1113Full:
		return true
	case WebSnippetUpdateLibraryJquery1113Trim:
		return true
	case WebSnippetUpdateLibraryJquery164Full:
		return true
	case WebSnippetUpdateLibraryJquery164Trim:
		return true
	case WebSnippetUpdateLibraryNone:
		return true
	default:
		return false
	}
}

// Defines values for WebSnippetUpdateVisitorIdLocatorType.
const (
	WebSnippetUpdateVisitorIdLocatorTypeCookie       WebSnippetUpdateVisitorIdLocatorType = "cookie"
	WebSnippetUpdateVisitorIdLocatorTypeJs           WebSnippetUpdateVisitorIdLocatorType = "js"
	WebSnippetUpdateVisitorIdLocatorTypeLocalStorage WebSnippetUpdateVisitorIdLocatorType = "localStorage"
	WebSnippetUpdateVisitorIdLocatorTypeQuery        WebSnippetUpdateVisitorIdLocatorType = "query"
)

// Valid indicates whether the value is a known member of the WebSnippetUpdateVisitorIdLocatorType enum.
func (e WebSnippetUpdateVisitorIdLocatorType) Valid() bool {
	switch e {
	case WebSnippetUpdateVisitorIdLocatorTypeCookie:
		return true
	case WebSnippetUpdateVisitorIdLocatorTypeJs:
		return true
	case WebSnippetUpdateVisitorIdLocatorTypeLocalStorage:
		return true
	case WebSnippetUpdateVisitorIdLocatorTypeQuery:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Code     *string                 `json:"code,omitempty"`
	Message  *string                 `json:"message,omitempty"`
	Messages *map[string]interface{} `json:"messages,omitempty"`
	Uuid     *openapi_types.UUID     `json:"uuid,omitempty"`
}

// Project defines model for Project.
type Project struct {
	// AccountId The account the Project is associated with
	AccountId *int64 `json:"account_id,omitempty"`

	// ConfidenceThreshold The significance level...
	ConfidenceThreshold *float64 `json:"confidence_threshold,omitempty"`

	// Created The time that the Project was originally created
	Created *time.Time `json:"created,omitempty"`

	// DcpServiceId The ID of a Dynamic Customer Profile Service associated with this Project
	DcpServiceId *int64 `json:"dcp_service_id,omitempty"`

	// Description A short description of the Project
	Description *string `json:"description,omitempty"`

	// Id The unique identifier for the Project
	Id *int64 `json:"id,omitempty"`

	// IsClassic If is_classic is true it means that the project doesn't have Optimizely X enabled.
	IsClassic *bool `json:"is_classic,omitempty"`

	// IsFlagsEnabled If is_flags_enabled is true, this project uses the new Flags-First user experience.
	IsFlagsEnabled *bool `json:"is_flags_enabled,omitempty"`

	// LastModified The time the Project was last modified
	LastModified *time.Time `json:"last_modified,omitempty"`

	// Name The name of the Project
	Name string `json:"name"`

	// Platform The platform of the Project
	Platform *ProjectPlatform `json:"platform,omitempty"`

	// Sdks For Full Stack, Mobile, and OTT projects, the language used for the SDK
	Sdks *[]ProjectSdks `json:"sdks,omitempty"`

	// SocketToken The token used to identify your mobile app to Optimizely (mobile only)
	SocketToken *string `json:"socket_token,omitempty"`

	// Status The current status of the Project
	Status *ProjectStatus `json:"status,omitempty"`

	// ThirdPartyPlatform The third party platform with which the project is intended to be used.
	ThirdPartyPlatform *ProjectThirdPartyPlatform `json:"third_party_platform,omitempty"`
	WebSnippet         *WebSnippet                `json:"web_snippet,omitempty"`
}

// ProjectPlatform The platform of the Project
type ProjectPlatform string

// ProjectSdks defines model for Project.Sdks.
type ProjectSdks string

// ProjectStatus The current status of the Project
type ProjectStatus string

// ProjectThirdPartyPlatform The third party platform with which the project is intended to be used.
type ProjectThirdPartyPlatform string

// ProjectUpdate defines model for ProjectUpdate.
type ProjectUpdate struct {
	// AccountId The ID of the account the Project is associated with
	AccountId *int64 `json:"account_id,omitempty"`

	// ConfidenceThreshold The significance level...
	ConfidenceThreshold *float64 `json:"confidence_threshold,omitempty"`

	// DcpServiceId The ID of a Dynamic Customer Profile Service associated with this Project
	DcpServiceId *int64 `json:"dcp_service_id,omitempty"`

	// Description A short description of the Project
	Description *string `json:"description,omitempty"`

	// Name The name of the Project
	Name *string `json:"name,omitempty"`

	// Status The current status of the Project
	Status     *ProjectUpdateStatus `json:"status,omitempty"`
	WebSnippet *WebSnippetUpdate    `json:"web_snippet,omitempty"`
}

// ProjectUpdateStatus The current status of the Project
type ProjectUpdateStatus string

// WebSnippet defines model for WebSnippet.
type WebSnippet struct {
	// CodeRevision The current revision number of the Project snippet
	CodeRevision *int `json:"code_revision,omitempty"`

	// EnableForceVariation Enables the option to force yourself into a specific variation on any page
	EnableForceVariation *bool `json:"enable_force_variation,omitempty"`

	// ExcludeDisabledExperiments Set to true to remove paused and draft Experiment from the snippet
	ExcludeDisabledExperiments *bool `json:"exclude_disabled_experiments,omitempty"`

	// ExcludeNames Set to true to mask descriptive names
	ExcludeNames *bool `json:"exclude_names,omitempty"`

	// IncludeJquery Set to true to include jQuery in your snippet
	IncludeJquery *bool `json:"include_jquery,omitempty"`

	// IpAnonymization Set to true to change the last octet of IP addresses to 0 prior to logging
	IpAnonymization *bool `json:"ip_anonymization,omitempty"`

	// IpFilter A regular expression matching ip addresses for filtering out visitors.
	IpFilter *string `json:"ip_filter,omitempty"`

	// JsFileSize The current size in bytes of the Project snippet
	JsFileSize *int `json:"js_file_size,omitempty"`

	// Library The prefered jQuery library version you would like to use with your snippet.
	Library *WebSnippetLibrary `json:"library,omitempty"`

	// ProjectJavascript The javascript code which runs before Optimizely on all pages
	ProjectJavascript *string `json:"project_javascript,omitempty"`

	// VisitorIdLocatorName (BETA) The name of said identifier that locates the visitor id
	VisitorIdLocatorName *string `json:"visitor_id_locator_name,omitempty"`

	// VisitorIdLocatorType (BETA) The type of identifer where the visitor id is located
	VisitorIdLocatorType *WebSnippetVisitorIdLocatorType `json:"visitor_id_locator_type,omitempty"`
}

// WebSnippetLibrary The prefered jQuery library version you would like to use with your snippet.
type WebSnippetLibrary string

// WebSnippetVisitorIdLocatorType (BETA) The type of identifer where the visitor id is located
type WebSnippetVisitorIdLocatorType string

// WebSnippetUpdate defines model for WebSnippetUpdate.
type WebSnippetUpdate struct {
	// EnableForceVariation Enables the option to force yourself into a specific variation on any page
	EnableForceVariation *bool `json:"enable_force_variation,omitempty"`

	// ExcludeDisabledExperiments Set to true to remove paused and draft Experiment from the snippet
	ExcludeDisabledExperiments *bool `json:"exclude_disabled_experiments,omitempty"`

	// ExcludeNames Set to true to mask descriptive names
	ExcludeNames *bool `json:"exclude_names,omitempty"`

	// IncludeJquery Set to true to include jQuery in your snippet
	IncludeJquery *bool `json:"include_jquery,omitempty"`

	// IpAnonymization Set to true to change the last octet of IP addresses to 0 prior to logging
	IpAnonymization *bool `json:"ip_anonymization,omitempty"`

	// IpFilter A regular expression matching ip addresses for filtering out visitors.
	IpFilter *string `json:"ip_filter,omitempty"`

	// Library The prefered jQuery library version you would like to use with your snippet.
	Library *WebSnippetUpdateLibrary `json:"library,omitempty"`

	// ProjectJavascript The javascript code which runs before Optimizely on all pages
	ProjectJavascript *string `json:"project_javascript,omitempty"`

	// VisitorIdLocatorName (BETA) The name of said identifier that locates the visitor id
	VisitorIdLocatorName *string `json:"visitor_id_locator_name,omitempty"`

	// VisitorIdLocatorType (BETA) The type of identifer where the visitor id is located
	VisitorIdLocatorType *WebSnippetUpdateVisitorIdLocatorType `json:"visitor_id_locator_type,omitempty"`
}

// WebSnippetUpdateLibrary The prefered jQuery library version you would like to use with your snippet.
type WebSnippetUpdateLibrary string

// WebSnippetUpdateVisitorIdLocatorType (BETA) The type of identifer where the visitor id is located
type WebSnippetUpdateVisitorIdLocatorType string

// Page defines model for page.
type Page = int

// PerPage defines model for per_page.
type PerPage = int

// ListProjectsParams defines parameters for ListProjects.
type ListProjectsParams struct {
	// PerPage Optional pagination argument that specifies the maximum number of objects to return per request
	PerPage *PerPage `form:"per_page,omitempty" json:"per_page,omitempty"`

	// Page Optional pagination argument that specifies the page to return. The default value is 1.
	Page *Page `form:"page,omitempty" json:"page,omitempty"`
}

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = Project

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody = ProjectUpdate

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListProjects request
	ListProjects(ctx context.Context, params *ListProjectsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateProjectWithBody request with any body
	CreateProjectWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateProject(ctx context.Context, body CreateProjectJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetProject request
	GetProject(ctx context.Context, projectId int64, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateProjectWithBody request with any body
	UpdateProjectWithBody(ctx context.Context, projectId int64, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateProject(ctx context.Context, projectId int64, body UpdateProjectJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListProjects(ctx context.Context, params *ListProjectsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListProjectsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateProjectWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateProjectRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateProject(ctx context.Context, body CreateProjectJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateProjectRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetProject(ctx context.Context, projectId int64, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetProjectRequest(c.Server, projectId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateProjectWithBody(ctx context.Context, projectId int64, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateProjectRequestWithBody(c.Server, projectId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateProject(ctx context.Context, projectId int64, body UpdateProjectJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateProjectRequest(c.Server, projectId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListProjectsRequest generates requests for ListProjects
func NewListProjectsRequest(server string, params *ListProjectsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/projects")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.PerPage != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "per_page", *params.PerPage, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateProjectRequest calls the generic CreateProject builder with application/json body
func NewCreateProjectRequest(server string, body CreateProjectJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateProjectRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateProjectRequestWithBody generates requests for CreateProject with any type of body
func NewCreateProjectRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/projects")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetProjectRequest generates requests for GetProject
func NewGetProjectRequest(server string, projectId int64) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "project_id", projectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int64"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/projects/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateProjectRequest calls the generic UpdateProject builder with application/json body
func NewUpdateProjectRequest(server string, projectId int64, body UpdateProjectJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateProjectRequestWithBody(server, projectId, "application/json", bodyReader)
}

// NewUpdateProjectRequestWithBody generates requests for UpdateProject with any type of body
func NewUpdateProjectRequestWithBody(server string, projectId int64, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "project_id", projectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int64"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/projects/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListProjectsWithResponse request
	ListProjectsWithResponse(ctx context.Context, params *ListProjectsParams, reqEditors ...RequestEditorFn) (*ListProjectsResponse, error)

	// CreateProjectWithBodyWithResponse request with any body
	CreateProjectWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateProjectResponse, error)

	CreateProjectWithResponse(ctx context.Context, body CreateProjectJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateProjectResponse, error)

	// GetProjectWithResponse request
	GetProjectWithResponse(ctx context.Context, projectId int64, reqEditors ...RequestEditorFn) (*GetProjectResponse, error)

	// UpdateProjectWithBodyWithResponse request with any body
	UpdateProjectWithBodyWithResponse(ctx context.Context, projectId int64, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateProjectResponse, error)

	UpdateProjectWithResponse(ctx context.Context, projectId int64, body UpdateProjectJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateProjectResponse, error)
}

type ListProjectsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Project
	JSON401      *Error
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r ListProjectsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListProjectsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateProjectResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Project
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r CreateProjectResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateProjectResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetProjectResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Project
	JSON400      *Error
	JSON403      *Error
	JSON404      *Error
}

// Status returns HTTPResponse.Status
func (r GetProjectResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetProjectResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateProjectResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Project
	JSON400      *Error
	JSON401      *Error
	JSON403      *Error
	JSON404      *Error
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r UpdateProjectResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateProjectResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListProjectsWithResponse request returning *ListProjectsResponse
func (c *ClientWithResponses) ListProjectsWithResponse(ctx context.Context, params *ListProjectsParams, reqEditors ...RequestEditorFn) (*ListProjectsResponse, error) {
	rsp, err := c.ListProjects(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListProjectsResponse(rsp)
}

// CreateProjectWithBodyWithResponse request with arbitrary body returning *CreateProjectResponse
func (c *ClientWithResponses) CreateProjectWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateProjectResponse, error) {
	rsp, err := c.CreateProjectWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateProjectResponse(rsp)
}

func (c *ClientWithResponses) CreateProjectWithResponse(ctx context.Context, body CreateProjectJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateProjectResponse, error) {
	rsp, err := c.CreateProject(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateProjectResponse(rsp)
}

// GetProjectWithResponse request returning *GetProjectResponse
func (c *ClientWithResponses) GetProjectWithResponse(ctx context.Context, projectId int64, reqEditors ...RequestEditorFn) (*GetProjectResponse, error) {
	rsp, err := c.GetProject(ctx, projectId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetProjectResponse(rsp)
}

// UpdateProjectWithBodyWithResponse request with arbitrary body returning *UpdateProjectResponse
func (c *ClientWithResponses) UpdateProjectWithBodyWithResponse(ctx context.Context, projectId int64, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateProjectResponse, error) {
	rsp, err := c.UpdateProjectWithBody(ctx, projectId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateProjectResponse(rsp)
}

func (c *ClientWithResponses) UpdateProjectWithResponse(ctx context.Context, projectId int64, body UpdateProjectJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateProjectResponse, error) {
	rsp, err := c.UpdateProject(ctx, projectId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateProjectResponse(rsp)
}

// ParseListProjectsResponse parses an HTTP response from a ListProjectsWithResponse call
func ParseListProjectsResponse(rsp *http.Response) (*ListProjectsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListProjectsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Project
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseCreateProjectResponse parses an HTTP response from a CreateProjectWithResponse call
func ParseCreateProjectResponse(rsp *http.Response) (*CreateProjectResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateProjectResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Project
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetProjectResponse parses an HTTP response from a GetProjectWithResponse call
func ParseGetProjectResponse(rsp *http.Response) (*GetProjectResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetProjectResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Project
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseUpdateProjectResponse parses an HTTP response from a UpdateProjectWithResponse call
func ParseUpdateProjectResponse(rsp *http.Response) (*UpdateProjectResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateProjectResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Project
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
